services:
  server:
    build: ./server
    container_name: geocms-server
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=development
      - DB_URI=${DB_URI}

  client:
    build: ./client
    container_name: geocms-client
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    container_name: geocms-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server
